/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalLoginRouteImport } from './routes/portal-login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAbsenteeReportRouteImport } from './routes/_authenticated/admin.absentee-report'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin.attendance'
import { Route as AuthenticatedAdminFeesRouteImport } from './routes/_authenticated/admin.fees'
import { Route as AuthenticatedAdminHostelRouteImport } from './routes/_authenticated/admin.hostel'
import { Route as AuthenticatedAdminProgramsRouteImport } from './routes/_authenticated/admin.programs'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminStruckOffRouteImport } from './routes/_authenticated/admin.struck-off'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminTimetableRouteImport } from './routes/_authenticated/admin.timetable'
import { Route as AuthenticatedAdminWebsiteRouteImport } from './routes/_authenticated/admin.website'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedTeacherAttendanceRouteImport } from './routes/_authenticated/teacher.attendance'
import { Route as AuthenticatedTeacherExamsRouteImport } from './routes/_authenticated/teacher.exams'
import { Route as AuthenticatedAdminExamsIndexRouteImport } from './routes/_authenticated/admin.exams.index'
import { Route as AuthenticatedAdminExamsExamIdRouteImport } from './routes/_authenticated/admin.exams.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal-login',
  path: '/portal-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAbsenteeReportRoute =
  AuthenticatedAdminAbsenteeReportRouteImport.update({
    id: '/absentee-report',
    path: '/absentee-report',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeesRoute = AuthenticatedAdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminHostelRoute =
  AuthenticatedAdminHostelRouteImport.update({
    id: '/hostel',
    path: '/hostel',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProgramsRoute =
  AuthenticatedAdminProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStruckOffRoute =
  AuthenticatedAdminStruckOffRouteImport.update({
    id: '/struck-off',
    path: '/struck-off',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTimetableRoute =
  AuthenticatedAdminTimetableRouteImport.update({
    id: '/timetable',
    path: '/timetable',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteRoute =
  AuthenticatedAdminWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherAttendanceRoute =
  AuthenticatedTeacherAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherExamsRoute =
  AuthenticatedTeacherExamsRouteImport.update({
    id: '/exams',
    path: '/exams',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedAdminExamsIndexRoute =
  AuthenticatedAdminExamsIndexRouteImport.update({
    id: '/exams/',
    path: '/exams/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExamsExamIdRoute =
  AuthenticatedAdminExamsExamIdRouteImport.update({
    id: '/exams/$examId',
    path: '/exams/$examId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal-login': typeof PortalLoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/admin/absentee-report': typeof AuthenticatedAdminAbsenteeReportRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/hostel': typeof AuthenticatedAdminHostelRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/struck-off': typeof AuthenticatedAdminStruckOffRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/timetable': typeof AuthenticatedAdminTimetableRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/teacher/attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/teacher/exams': typeof AuthenticatedTeacherExamsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal-login': typeof PortalLoginRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/absentee-report': typeof AuthenticatedAdminAbsenteeReportRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/hostel': typeof AuthenticatedAdminHostelRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/struck-off': typeof AuthenticatedAdminStruckOffRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/timetable': typeof AuthenticatedAdminTimetableRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/teacher/attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/teacher/exams': typeof AuthenticatedTeacherExamsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/admin/exams': typeof AuthenticatedAdminExamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal-login': typeof PortalLoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/_authenticated/admin/absentee-report': typeof AuthenticatedAdminAbsenteeReportRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/_authenticated/admin/hostel': typeof AuthenticatedAdminHostelRoute
  '/_authenticated/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/struck-off': typeof AuthenticatedAdminStruckOffRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/timetable': typeof AuthenticatedAdminTimetableRoute
  '/_authenticated/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/_authenticated/teacher/attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/_authenticated/teacher/exams': typeof AuthenticatedTeacherExamsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/_authenticated/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal-login'
    | '/admin'
    | '/portal'
    | '/teacher'
    | '/admin/absentee-report'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/hostel'
    | '/admin/programs'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/struck-off'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin/website'
    | '/teacher/attendance'
    | '/teacher/exams'
    | '/admin/'
    | '/teacher/'
    | '/admin/exams/$examId'
    | '/admin/exams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal-login'
    | '/portal'
    | '/admin/absentee-report'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/hostel'
    | '/admin/programs'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/struck-off'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin/website'
    | '/teacher/attendance'
    | '/teacher/exams'
    | '/admin'
    | '/teacher'
    | '/admin/exams/$examId'
    | '/admin/exams'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal-login'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/teacher'
    | '/_authenticated/admin/absentee-report'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/fees'
    | '/_authenticated/admin/hostel'
    | '/_authenticated/admin/programs'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/struck-off'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/timetable'
    | '/_authenticated/admin/website'
    | '/_authenticated/teacher/attendance'
    | '/_authenticated/teacher/exams'
    | '/_authenticated/admin/'
    | '/_authenticated/teacher/'
    | '/_authenticated/admin/exams/$examId'
    | '/_authenticated/admin/exams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalLoginRoute: typeof PortalLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-login': {
      id: '/portal-login'
      path: '/portal-login'
      fullPath: '/portal-login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/absentee-report': {
      id: '/_authenticated/admin/absentee-report'
      path: '/absentee-report'
      fullPath: '/admin/absentee-report'
      preLoaderRoute: typeof AuthenticatedAdminAbsenteeReportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fees': {
      id: '/_authenticated/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AuthenticatedAdminFeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hostel': {
      id: '/_authenticated/admin/hostel'
      path: '/hostel'
      fullPath: '/admin/hostel'
      preLoaderRoute: typeof AuthenticatedAdminHostelRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/programs': {
      id: '/_authenticated/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AuthenticatedAdminProgramsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/struck-off': {
      id: '/_authenticated/admin/struck-off'
      path: '/struck-off'
      fullPath: '/admin/struck-off'
      preLoaderRoute: typeof AuthenticatedAdminStruckOffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/timetable': {
      id: '/_authenticated/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AuthenticatedAdminTimetableRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website': {
      id: '/_authenticated/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/attendance': {
      id: '/_authenticated/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof AuthenticatedTeacherAttendanceRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/exams': {
      id: '/_authenticated/teacher/exams'
      path: '/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof AuthenticatedTeacherExamsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/admin/exams/': {
      id: '/_authenticated/admin/exams/'
      path: '/exams'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AuthenticatedAdminExamsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exams/$examId': {
      id: '/_authenticated/admin/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/admin/exams/$examId'
      preLoaderRoute: typeof AuthenticatedAdminExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAbsenteeReportRoute: typeof AuthenticatedAdminAbsenteeReportRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminFeesRoute: typeof AuthenticatedAdminFeesRoute
  AuthenticatedAdminHostelRoute: typeof AuthenticatedAdminHostelRoute
  AuthenticatedAdminProgramsRoute: typeof AuthenticatedAdminProgramsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminStruckOffRoute: typeof AuthenticatedAdminStruckOffRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTimetableRoute: typeof AuthenticatedAdminTimetableRoute
  AuthenticatedAdminWebsiteRoute: typeof AuthenticatedAdminWebsiteRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminExamsExamIdRoute: typeof AuthenticatedAdminExamsExamIdRoute
  AuthenticatedAdminExamsIndexRoute: typeof AuthenticatedAdminExamsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAbsenteeReportRoute: AuthenticatedAdminAbsenteeReportRoute,
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminFeesRoute: AuthenticatedAdminFeesRoute,
  AuthenticatedAdminHostelRoute: AuthenticatedAdminHostelRoute,
  AuthenticatedAdminProgramsRoute: AuthenticatedAdminProgramsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminStruckOffRoute: AuthenticatedAdminStruckOffRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminTimetableRoute: AuthenticatedAdminTimetableRoute,
  AuthenticatedAdminWebsiteRoute: AuthenticatedAdminWebsiteRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminExamsExamIdRoute: AuthenticatedAdminExamsExamIdRoute,
  AuthenticatedAdminExamsIndexRoute: AuthenticatedAdminExamsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherAttendanceRoute: typeof AuthenticatedTeacherAttendanceRoute
  AuthenticatedTeacherExamsRoute: typeof AuthenticatedTeacherExamsRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherAttendanceRoute: AuthenticatedTeacherAttendanceRoute,
  AuthenticatedTeacherExamsRoute: AuthenticatedTeacherExamsRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalLoginRoute: PortalLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
